/* convert WFG format to JSON */
import {nodefs,writeChanged,readTextLines,readTextContent} from 'pitaka/cli';
import {parseIdiomEntryWFG} from './src/wfg-idioms.js'


await nodefs;
const srcdir='raw/'
const outdir='off/';
//https://drive.google.com/drive/folders/11-nEz4xlm3nT25bOrj6l7WRKA1faix8X 教育部成語典[5153].7z
const srcfile='dict_idioms-wfg.txt'; //test file wfg-format.txt

const entryId = JSON.parse(readTextContent(srcdir+'entry_id.json'));//Entry's Id generated by tidy.js
const rawcontent=readTextContent(srcdir+srcfile);
const entries=rawcontent.split('</>\n'); //MDict entry Separator
const ctx={entryId,section:'unparsed'};
const out=[];
entries.forEach(entry=>{
	const obj=parseIdiomEntryWFG(entry,ctx); 
	if (!obj) return;
	out.push(obj);
});

if (writeChanged(outdir+srcfile.replace('.txt','.off'),JSON.stringify(out,'',' '))) {
	console.log('written',out.length);
}



